[tool.poetry]
name = "tools-image"
version = "0.1.0"
description = "Tools for formatting/linting/etc."
authors = ["Gordon Greene"]
license = "MIT"
readme = "README.md"
packages = [{include = "tools_image"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
